dist: trusty

sudo: required

addon_shortcuts:
  xcode64: &xcode64
    apt:
      packages:

  clang38: &clang38
    apt:
      sources:
        - llvm-toolchain-trusty-3.8
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
      packages:
        - clang-3.8
        - libc++-dev

  clang50: &clang50
    apt:
      sources:
        - llvm-toolchain-trusty-5.0
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
      packages:
        - clang-5.0
        - libc++-dev

  clang60: &clang60
    apt:
      sources:
        - llvm-toolchain-trusty-6.0
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
      packages:
        - clang-6.0
        - libc++-dev

  gcc48: &gcc48
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8

  gcc6: &gcc6
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-6

  gcc7: &gcc7
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-7

  gcc8: &gcc8
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-8

addons:
  apt:
    update: true
    packages:
      - cmake

before_install:
  - curl -L http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main' | sudo tee /etc/apt/sources.list

matrix:
  include:
    - { env: 'CXX_STANDARD=11 CXX=g++-4.8 CXXFLAGS="-std=c++11"', addons: *gcc48 }
    - { env: 'CXX_STANDARD=11 CXX=g++-6', addons: *gcc6 }
    - { env: 'CXX_STANDARD=11 CXX=g++-6 CXXFLAGS="-DNO_DEPRECATED=YES"', addons: *gcc6 }
    - { env: 'CXX_STANDARD=11 CXX=g++-7', addons: *gcc7 }
    - { env: 'CXX_STANDARD=11 CXX=g++-7 CXXFLAGS="-DNO_DEPRECATED=YES"', addons: *gcc7 }
    - { env: 'CXX_STANDARD=17 CXX=g++-8', addons: *gcc8 }
    - { env: 'CXX_STANDARD=17 CXX=g++-8 CXXFLAGS="-DNO_DEPRECATED=YES"', addons: *gcc8 }
    - { env: 'CXX_STANDARD=11 CXX=clang++-3.8', addons: *clang38 }
    - { env: 'CXX_STANDARD=11 CXX=clang++-5.0', addons: *clang50 }
    - { env: 'CXX_STANDARD=11 CXX=clang++-6.0', addons: *clang60 }
    - { env: 'CXX_STANDARD=11 CXX=clang++', compiler: clang, osx_image: xcode6.4', addons: *xcode64}

script:
  - cd tests/build/cmake
  - cmake .
  - cmake --build . --config Release
  - ctest -C Release -V -j

