build: false

os: Visual Studio 2015

platform:
  - x64
  - x86

environment:
  matrix:
    - MINICONDA: C:\jsoncons-conda

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%

install:
  - cmake -G "NMake Makefiles" -D BUILD_TESTS=1 -D CMAKE_BUILD_TYPE=Release .
  - cmake --build . --target test_jsoncons --config Release
  # - nmake test_jsoncons
  - cd tests

build_script:
  - .\test_jsoncons
