blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/danielaparker/jsoncons/discussions
    about: Ask questions and initiate discussions with other community members
